name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t py_flash:${{github.sha}} -f py_flash/Dockerfile .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
    - name: tag docker image
      run: docker tag py_flash:'${{github.sha}}' '${{ secrets.DOCKER_USERNAME }}'/py_flash:'${{github.sha}}'
    - name: Push Docker image
      run: docker push '${{ secrets.DOCKER_USERNAME }}'/py_flash:'${{github.sha}}'
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.SECRET_AZURE_CRE }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Authenticate using Service Principal
      run: |
        export ARM_CLIENT_ID=${{ secrets.CLIENTID }}
        export ARM_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
        export ARM_TENANT_ID=${{ secrets.TENANT_ID }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
