name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t py_flash:${{github.sha}} -f py_flash/Dockerfile .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}

    - name: Tag Docker image
      run: |
        docker tag py_flash:'${{github.sha}}' '${{ secrets.DOCKER_USERNAME }}'/py_flash:'${{github.sha}}'
        docker tag py_flash:'${{github.sha}}' '${{ secrets.DOCKER_USERNAME }}'/py_flash:latest

    - name: Push Docker image
      run: |
        docker push '${{ secrets.DOCKER_USERNAME }}'/py_flash:'${{github.sha}}'
        docker push '${{ secrets.DOCKER_USERNAME }}'/py_flash:latest
    -  name: Scan for vulnerabilities
       uses: crazy-max/ghaction-container-scan@v3
       with:
         image: '${{ secrets.DOCKER_USERNAME }}/py_flash:${{github.sha}}' 

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.SECRET_AZURE_CRE }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Authenticate using Service Principal
      run: |
        export ARM_CLIENT_ID=${{ secrets.CLIENTID }}
        export ARM_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
        export ARM_TENANT_ID=${{ secrets.TENANT_ID }}

    - name: Terraform Init
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      run: terraform init
    - name: Terraform Apply
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}  
        ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}   
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      run: terraform apply -auto-approve -var subscription_id=${{ secrets.SUBSCRIPTION_ID }} -var client_id=${{ secrets.CLIENTID }} -var client_secret=${{ secrets.CLIENT_SECRET }} -var tenant_id=${{ secrets.TENANT_ID }} -var username=${{ secrets.VM_USERNAME }} -var password=${{ secrets.VM_PASSWORD }}
   
